In [1]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import GridSearchCV

# from keras.models import Sequential
# from keras.layers import Dense
# from keras.optimizers import Adam
# from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
], dtype="float32")

y = np.array([0, 0, 0, 1], dtype="float32")

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y

array([0., 0., 0., 1.], dtype=float32)

In [5]:
model = Sequential()

Metal device set to: Apple M1 Max


2022-05-09 19:55:59.643405: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-09 19:55:59.643730: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [6]:
model.add(Dense(1, input_dim=2, activation="sigmoid"))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])

/Users/dowonlee_1/miniforge3/envs/tf25/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [9]:
def get_model():
    model = Sequential()
    model.add(Dense(1, input_dim=2, activation="sigmoid"))
    model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])
    print(model)
    return model

In [10]:
_model = KerasClassifier(build_fn=get_model, verbose=1)
param_grid = dict(nb_epoch=[3], 
                  batch_size=[5])
grid = GridSearchCV(estimator=_model, param_grid=param_grid, cv=4)

In [11]:
grid_result = grid.fit(X, y)

/Users/dowonlee_1/miniforge3/envs/tf25/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
2022-05-09 19:56:00.399490: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-05-09 19:56:00.401620: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-05-09 19:56:00.509628: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 1s 1s/step - loss: 0.7740 - acc: 0.3333


2022-05-09 19:56:01.479072: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 46ms/step - loss: 0.2908 - acc: 1.0000


/Users/dowonlee_1/miniforge3/envs/tf25/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
2022-05-09 19:56:01.897677: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-05-09 19:56:01.978666: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
/Users/dowonlee_1/miniforge3/envs/tf25/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


1/1 [==============================] - 0s 48ms/step - loss: 0.7923 - acc: 0.0000e+00


2022-05-09 19:56:02.096542: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-05-09 19:56:02.178311: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
/Users/dowonlee_1/miniforge3/envs/tf25/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
2022-05-09 19:56:02.295957: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 50ms/step - loss: 1.4610 - acc: 0.0000e+00


2022-05-09 19:56:02.401443: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-05-09 19:56:02.522475: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 272ms/step - loss: 0.7538 - acc: 0.5000


In [12]:
grid_result

GridSearchCV(cv=4,
             estimator=<tensorflow.python.keras.wrappers.scikit_learn.KerasClassifier object at 0x2b07d5910>,
             param_grid={'batch_size': [5], 'nb_epoch': [3]})

In [13]:
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 215ms/step - loss: 0.7538 - acc: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.7241 - acc: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6956 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6684 - acc: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6423 - acc: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6175 - acc: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.5939 - acc: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.5715 - acc: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.5501 - acc: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.5297 - acc: 0.5000
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 0.510

2022-05-09 19:56:02.906064: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


Epoch 22/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3497 - acc: 1.0000
Epoch 23/100
1/1 [==============================] - 0s 5ms/step - loss: 0.3391 - acc: 1.0000
Epoch 24/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3290 - acc: 1.0000
Epoch 25/100
1/1 [==============================] - 0s 5ms/step - loss: 0.3194 - acc: 1.0000
Epoch 26/100
1/1 [==============================] - 0s 5ms/step - loss: 0.3103 - acc: 1.0000
Epoch 27/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3017 - acc: 1.0000
Epoch 28/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2934 - acc: 1.0000
Epoch 29/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2856 - acc: 1.0000
Epoch 30/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2781 - acc: 1.0000
Epoch 31/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2710 - acc: 1.0000
Epoch 32/100
1/1 [==============================] - 0s 6ms/step - loss

In [14]:
pred = model.predict(X)
pred

2022-05-09 19:56:03.659001: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


array([[0.00178979],
       [0.09037358],
       [0.1151342 ],
       [0.8781948 ]], dtype=float32)

In [15]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [16]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [17]:
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [18]:
np.sum(predict03)

4

In [19]:
acc = np.sum(predict03) / 4
acc

1.0

In [20]:
arr=np.array([[0,1]], dtype="float32")
pred = model.predict(arr)
pred

array([[0.09037358]], dtype=float32)

In [21]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]]


In [22]:
arr=np.array([[1,1]], dtype="float32")
pred = model.predict(arr)
pred

array([[0.8781948]], dtype=float32)

In [23]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[1]]
