In [6]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import GridSearchCV

# from keras.models import Sequential
# from keras.layers import Dense
# from keras.optimizers import Adam
# from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [7]:
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
], dtype="float32")

y = np.array([0, 0, 0, 1], dtype="float32")

In [8]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [9]:
y

array([0., 0., 0., 1.], dtype=float32)

In [10]:
model = Sequential()

In [11]:
model.add(Dense(1, input_dim=2, activation="sigmoid"))

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])

In [14]:
def get_model():
    model = Sequential()
    model.add(Dense(1, input_dim=2, activation="sigmoid"))
    model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])
    print(model)
    return model

In [15]:
_model = KerasClassifier(build_fn=get_model, verbose=1)
param_grid = dict(nb_epoch=[3], 
                  batch_size=[5])
grid = GridSearchCV(estimator=_model, param_grid=param_grid, cv=4)

In [16]:
grid_result = grid.fit(X, y)

1/1 [==============================] - 0s 601us/step - loss: 0.8440 - acc: 0.5000


In [28]:
grid_result

GridSearchCV(cv=4,
             estimator=<tensorflow.python.keras.wrappers.scikit_learn.KerasClassifier object at 0x7fca7a7986d0>,
             param_grid={'batch_size': [5], 'nb_epoch': [3]})

In [17]:
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 800us/step - loss: 0.7749 - acc: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7404 - acc: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7094 - acc: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6818 - acc: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6573 - acc: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6349 - acc: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6136 - acc: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5928 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 716us/step - loss: 0.5723 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5522 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 831us/step - loss: 0

1/1 [==============================] - 0s 1ms/step - loss: 0.1195 - acc: 1.0000
Epoch 81/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1179 - acc: 1.0000
Epoch 82/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1164 - acc: 1.0000
Epoch 83/100
1/1 [==============================] - 0s 3ms/step - loss: 0.1149 - acc: 1.0000
Epoch 84/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1135 - acc: 1.0000
Epoch 85/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1120 - acc: 1.0000
Epoch 86/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1106 - acc: 1.0000
Epoch 87/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1093 - acc: 1.0000
Epoch 88/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1079 - acc: 1.0000
Epoch 89/100
1/1 [==============================] - 0s 766us/step - loss: 0.1066 - acc: 1.0000
Epoch 90/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1053 - 

In [18]:
pred = model.predict(X)
pred

array([[0.0021666 ],
       [0.09620187],
       [0.11982122],
       [0.869686  ]], dtype=float32)

In [19]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [20]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [21]:
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [22]:
np.sum(predict03)

4

In [23]:
acc = np.sum(predict03) / 4
acc

1.0

In [24]:
arr=np.array([[0,1]], dtype="float32")
pred = model.predict(arr)
pred

array([[0.09620187]], dtype=float32)

In [25]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[0]]


In [26]:
arr=np.array([[1,1]], dtype="float32")
pred = model.predict(arr)
pred

array([[0.869686]], dtype=float32)

In [27]:
predict01 = np.where(pred > 0.5, 1, 0)
print("=" * 30)
print("predict01")
print(predict01)

predict01
[[1]]
