'''
https://velog.io/@tjdtnsu/PyTorch-%EA%B8%B0%EC%B4%88-%ED%85%90%EC%84%9C-%EC%83%9D%EC%84%B1-%EB%B0%8F-%EC%A1%B0%EC%9E%91%ED%95%98%EA%B8%B0
'''
## torch 불러오기

In [1]:
import torch
import numpy as np

## 텐서 생성

In [3]:
x_list = [[1., 2.],[3., 4.]]
x_numpy = np.array(x_list)
x = torch.tensor(x_list)

print("list \n", x_list)
print("numpy \n", x_numpy)
print("tensor \n", x)

list 
 [[1.0, 2.0], [3.0, 4.0]]
numpy 
 [[1. 2.]
 [3. 4.]]
tensor 
 tensor([[1., 2.],
        [3., 4.]])


## numpy와의 자료형 변환

In [ ]:
x_tensor_from_numpy = torch.from_numpy(x_numpy)
x_numpy_from_tensor = x.numpy()

print("tensor_from_numpy \n", x_tensor_from_numpy)
print("numpy_from_tensor \n", x_numpy_from_tensor)

## 특정 값으로의 텐서 생성

In [5]:
x23_zeros = torch.zeros(2, 3)
x23_ones = torch.ones(2, 3)
x23_rand = torch.rand(2, 3)

print("zeros_2by3 \n", x23_zeros)
print("ones_2by3 \n", x23_ones)
print("rand_2by3 \n", x23_rand)

zeros_2by3 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones_2by3 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
rand_2by3 
 tensor([[0.0651, 0.2972, 0.3915],
        [0.8914, 0.0623, 0.6619]])


## shape를 통한 텐서 생성

In [6]:
x_zeros = torch.zeros_like(x)
x_ones = torch.ones_like(x)

print("zeros_like \n", x_zeros)
print("ones_like \n", x_ones)

zeros_like 
 tensor([[0., 0.],
        [0., 0.]])
ones_like 
 tensor([[1., 1.],
        [1., 1.]])


## 값들의 간격을 정의하는 텐서 생성

In [7]:
x5 = torch.arange(5)

print("x5 \n", x5)

x5 
 tensor([0, 1, 2, 3, 4])


## shape 출력

In [8]:
print("x23_shape:", x23_rand.shape)
print("x5_shape:", x5.shape)

x23_shape: torch.Size([2, 3])
x5_shape: torch.Size([5])


## 텐서 간의 연산

In [9]:
print("matmul \n", x @ x)
print("mul \n", x * x)

matmul 
 tensor([[ 7., 10.],
        [15., 22.]])
mul 
 tensor([[ 1.,  4.],
        [ 9., 16.]])


## 텐서의 합과 평균

In [10]:
print("sum:", x.sum())
print("mean: ", x.mean())

sum: tensor(10.)
mean:  tensor(2.5000)


## 텐서 차원 조절

In [11]:
y = torch.rand(2, 1, 3, 2, 1, 5)

y_squeeze = torch.squeeze(y)
y_squeeze_0 = torch.squeeze(y, 1)
y_unsqueeze_0 = torch.unsqueeze(y, 0)
y_unsqueeze_3 = torch.unsqueeze(y, 3)

print("y_squeeze_shape:", y_squeeze.shape)
print("y_squeeze_0_shape:", y_squeeze_0.shape)
print("y_unsqueeze_0_shape:", y_unsqueeze_0.shape)
print("y_unsqueeze_3_shape:", y_unsqueeze_3.shape)

y_squeeze_shape: torch.Size([2, 3, 2, 5])
y_squeeze_0_shape: torch.Size([2, 3, 2, 1, 5])
y_unsqueeze_0_shape: torch.Size([1, 2, 1, 3, 2, 1, 5])
y_unsqueeze_3_shape: torch.Size([2, 1, 3, 1, 2, 1, 5])


## shape 변경


In [12]:
z = torch.rand(2, 3, 4)

z_6_view = z.view(6, -1)
z_6_reshape = z.reshape(6, -1)

print("z_6_view_shape:", z_6_view.shape)
print("z_6_reshape_shape:", z_6_reshape.shape)

z_6_view_shape: torch.Size([6, 4])
z_6_reshape_shape: torch.Size([6, 4])


## 텐서 차원 순서 변경

In [13]:
z_transpose = z.transpose(0, 2)
z_permute = z.permute(1, 2, 0)

print("z_transpose_shape:", z_transpose.shape)
print("z_permute_shape:", z_permute.shape)

z_transpose_shape: torch.Size([4, 3, 2])
z_permute_shape: torch.Size([3, 4, 2])
